/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.ashish.socketmodule;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;

import org.appcelerator.titanium.TiContext.OnLifecycleEvent;

import android.app.Activity;
import android.text.TextUtils;

import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;

import com.codebutler.android_websockets.WebSocketClient;


// This proxy can be created by calling Socketmoduleandroid.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule=SocketmoduleandroidModule.class)
public class WSProxy extends KrollProxy implements OnLifecycleEvent {
	private WebSocketClient client;
	private boolean connected = false;

	// Constructor
	public WSProxy() {
		super();
	}

	// Websocket stuff
	private void cleanup() {
		if (client == null || !connected) {
			return;
		}

		connected = false;
		try {
			client.disconnect();
		}
		catch (Exception ex) {
		}
		client = null;

		if (SocketmoduleandroidModule.DBG) {
			Log.d(SocketmoduleandroidModule.LCAT, "* websocket destroyed");
		}
	}

	// Context Lifecycle events
	@Override
	public void onStart(Activity activity) {
	}

	@Override
	public void onStop(Activity activity) {
	}

	@Override
	public void onPause(Activity activity) {
	}

	@Override
	public void onResume(Activity activity) {
	}

	@Override
	public void onDestroy(Activity activity) {
		cleanup();
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options) {
		super.handleCreationDict(options);
	}

	// Methods

	@Kroll.method
	public void open(Object[] args) {
		final KrollProxy self = this;

		if (args.length == 0) {
			throw new IllegalArgumentException("URI argument expected");
		}

		Object uri = args[0];
		if (!(uri instanceof String)) {
			throw new IllegalArgumentException("URI argument must be a string");
		}
		String wsUri = (String)uri;
		List<BasicNameValuePair> extraHeaders = new ArrayList<BasicNameValuePair>();
		if (args.length > 1) {
			Object proto = args[1];
			if (!(proto instanceof Object[])) {
				throw new IllegalArgumentException("protocols argument must be an array of strings");
			}
			Object[] protocols = (Object[])proto;
			for (int i = 0; i < protocols.length; i++) {
				if (!(protocols[i] instanceof String)) {
					throw new IllegalArgumentException("protocol at index " + i + " is not a string");
				}
			}
			BasicNameValuePair protocolHeader = new BasicNameValuePair("Sec-WebSocket-Protocol", TextUtils.join(", ", protocols));
			extraHeaders.add(protocolHeader);
		}
		try {
			if (SocketmoduleandroidModule.DBG) {
				Log.d(SocketmoduleandroidModule.LCAT, "* creating websocket");
			}

			URI wsURI = new URI(wsUri);
			Log.d(SocketmoduleandroidModule.LCAT, "* URI: " + wsURI);
			client = new WebSocketClient(wsURI, new WebSocketClient.Listener() {
				@Override
				public void onMessage(byte[] data) {
					if (client == null) {
						return;
					}
				}

				@Override
				public void onMessage(String message) {
					if (client == null) {
						return;
					}

					KrollDict event = new KrollDict();
					event.put("data", message);
					self.fireEvent("message", event);
				}

				@Override
				public void onError(Exception error) {
					if (client == null) {
						return;
					}

					if (SocketmoduleandroidModule.DBG) {
						Log.d(SocketmoduleandroidModule.LCAT, "* websocket error", error);
					}

					KrollDict event = new KrollDict();
					event.put("advice", "reconnect");
					event.put("error", error.toString());
					self.fireEvent("error", event);

					cleanup();
				}

				@Override
				public void onDisconnect(int code, String reason) {
					if (client == null) {
						return;
					}

					if (SocketmoduleandroidModule.DBG) {
						Log.d(SocketmoduleandroidModule.LCAT, "* creating disconnected; reason = " + reason + "; code = " + String.valueOf(code));
					}
					KrollDict event = new KrollDict();
					event.put("code", code);
					event.put("reason", reason);
					self.fireEvent("close", event);

					cleanup();
				}

				@Override
				public void onConnect() {
					connected = true;

					KrollDict event = new KrollDict();
					self.fireEvent("open", event);
				}
			}, extraHeaders);

			client.connect();
		}
		catch (URISyntaxException ex) {
			if (SocketmoduleandroidModule.DBG) {
				Log.d(SocketmoduleandroidModule.LCAT, "* creating exception", ex);
			}
			cleanup();
		}
	}

	@Kroll.method
	public void close() {
		cleanup();
	}

	@Kroll.method
	public void send(String message) {
		if (client != null && connected) {
			client.send(message);
		}
	}
}